/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Ace: typeof import('./components/render/Ace.vue')['default']
    Inspector: typeof import('./components/Inspector.vue')['default']
    Plain: typeof import('./components/render/PlainText.vue')['default']
    PlainText: typeof import('./components/render/PlainText.vue')['default']
    Viewer: typeof import('./components/Viewer.vue')['default']
  }
}
